export const BEGIN_AJAX_CALL = "BEGIN_AJAX_CALL";
export const AJAX_CALL_ERROR = "AJAX_CALL_ERROR";

export const LOAD_THOUGHTS_SUCCESS = "LOAD_THOUGHTS_SUCCESS";
export const CREATE_THOUGHTS_SUCCESS = "CREATE_THOUGHTS_SUCCESS";
export const UPDATE_THOUGHT_SUCCESS = "UPDATE_THOUGHT_SUCCESS";

export const LOAD_AUTHORS_SUCCESS = "LOAD_AUTHORS_SUCCESS";
